### ISSUE TITLE
Napply and ICS: widgets are sized 2x2 insted of 1x1

### ISSUE THREAD

**Issue by hobo2** [thibault/Miximum-apps#10]
First thank you for this really nice app, I am using it  every day!  ICS bug: Running android 4.0 napply widgets are sized 2x2 instead of 1x1 and so need way more space then necessary :(

**Comment by thibault** [comment]
Will check this when I have the time.

**Comment by alijc** [comment]
I suspect that the problem is due to the margins embedded in the widget background image.  
According to this page -- http://developer.android.com/guide/practices/ui_guidelines/widget_design.html --
Android 4.\* is automatically adding margins to the widgets.  And in some cases the doubled margins are enough to push the 1x1 widget into 2x2 territory.

It's just a theory though.  If I could build the app then I'd test out whether cropping the margins off of the widget would result in a 1x1 widget.

**Comment by nemo970** [comment]
Thibault, please correct that, if possible. This app is awesome, but I also have problem with just one widget taking 2x2 space.. (Xperia M, Android 4.1.2.). I think alijc is right, it appears that the icon itself is little bigger than Jelly Bean would like. Seems like not too difficult to fix. Thanks a lot!!

**Comment by alijc** [comment]
Try loading this:

https://docs.google.com/file/d/0B9U-sWlCndzVelJKeXJUVXJkckU/edit?usp=sharing

It ended up that the only change was to decrease the min size in the layout
meta file.

If this works for you then maybe Thibault will accept the pull request and
re-release the app.

Ali

**Comment by nemo970** [comment]
Yess, it works, perfect!! THANK YOU! :)

**Comment by thibault** [comment]
Sorry about the response time, just came back from holidays and catching up with huge todo list :|

Ok, I accepted the pull request. However, I don't have any spare time right now, plus I don't have any working Android development environnement, so I won't have the time to re-release the app any time soon.

**Comment by nsp** [comment]
I know that it's not trivial to get an android dev environment set up, but perhaps you could just send @alijc's APK over to the play store? I don't know how much work that is for you, though, so I'll just sideload @alijc's APK for now.

Thanks for a great app!

**Comment by alijc** [comment]
I don't think that will work.  I signed the app with a debug key, while
anything that goes into google play needs to be signed with a release key.
And, if I remember rightly, updates to an app have to be signed with the
same release key as the first version of the app.

**Comment by nsp** [comment]
Ah, of course. Nevermind, then.

**Comment by thibault** [comment]
@alijc is right, that's not just doable in a simple and quick way.
