### ISSUE TITLE
Set sound file in Napply

### ISSUE THREAD

**Issue by treare** [thibault/Miximum-apps#13]
Hi,

I found this wonderful app on f-droid. The problem is that in a Samsung stock rom it seems there's no way to choose a default sound for the Alarm app. The sound file that is used by default is very short. Since Napply only plays this file only once it's easy not to wake up. It would be nice that Napply can use it's own sound file.

**Comment by thibault** [comment]
Hi,

Thank you for your suggestion. Such a feature would be nice indeed, but I intend to keep Napply as minimalistic as possible, so I won't add this.

**Comment by treare** [comment]
Hi,

Since there's no custom rom for my machine (gt-i9205) and one beep isn't enough to wake me up i will have to find another app like this. Thanks anyway.
