### ISSUE TITLE
NAPPLY app freezes on start in LG Lucid

### ISSUE THREAD

**Issue by stanbartkus** [thibault/Miximum-apps#8]
Android 2.3.6

**Comment by stanbartkus** [comment]
screen shows:
Take a quick nap.....
You just need to know this.....
Credits
Do you like this app?
If you meet a bug.....

**Comment by thibault** [comment]
Thank for taking the time to post this issue. I'll try to reproduce the bug on similar phones, and let you know.

**Comment by stanbartkus** [comment]
I eventually got the App to work on my LG Lucid.

The wording of your instructions confused me vs. the other Apps I've launched.

I discovered I need to mount the App on a Home page via the Edit Function & then set it for my desired countdown before it's usable.

Bug Fix is to slightly reword the Instruction Page to make clearer for Droid beginners.

Thanks for writing.

Stan Bartkus 
773-588-2526
www.StanBartkus.biz 

Success comes to those whose actions outweigh their excuses.

-----Original Message-----
